# Generated by Django 5.1 on 2024-09-10 09:01

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AllEventList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniqueEventName', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('eventName', models.CharField(max_length=100)),
                ('eventDiscription', models.TextField()),
                ('eventImage', models.ImageField(upload_to='eventImages/')),
                ('club', models.CharField(choices=[('all', 'College'), ('insigniax', 'Insigniax'), ('parmarth', 'Parmarth'), ('fractal', 'Fractal'), ('robotics', 'Robotics')], max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('coordinators', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=100)),
                ('eventType', models.CharField(choices=[('normal', 'Normal Event'), ('individual', 'Individual Participation Event'), ('team', 'Team Participation Event')], max_length=10)),
                ('eventDate', models.DateField()),
                ('minTeamSize', models.IntegerField(default=1)),
                ('maxTeamSize', models.IntegerField(default=1)),
                ('dateAdded', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-dateAdded'],
            },
        ),
        migrations.CreateModel(
            name='IndividualEventRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.alleventlist')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TeamsRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teamName', models.CharField(max_length=100)),
                ('status', models.IntegerField(choices=[(1, 'Accepted'), (0, 'Req Pending')], default=0)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.alleventlist')),
                ('teamLeader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_lead_teams', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_registrations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
