# Generated by Django 5.1 on 2024-09-21 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alleventlist',
            old_name='eventDiscription',
            new_name='eventDescription',
        ),
    ]
